version: "3.8"

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    restart: always
    networks:
      - backend_users

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    restart: always
    networks:
      - backend_users

volumes:
  postgres_data:

networks:
  backend_users: