version: '3'

services:

  db:
    image: 'postgres:alpine'
    container_name: "db"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users 
    volumes:
      - "./data/postgress:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  api:
    build: 
      context: ./
    container_name: login
    links:
      - db
    ports:
      - "8080:8080"

    volumes:
      - ./:/app
    environment:
      - DEBUG=True