version: "3.8"

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on: []
    restart: always
    networks:
      - backend_users

volumes:
  postgres_data:

networks:
  backend_users: