name: Testes
on: push
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5
      - name: Creating env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3 -m venv env
          source env/bin/activate
      - name : install requirements
        run : pip install -r requirements.txt
      - name: setup local module
        run: pip install -e .
      - name: pytest
        run: python -m coverage run -m pytest --continue-on-collection-errors --junitxml=./junit.xml